2024-03-13 12:02:20,617 INFO    MainThread:27108 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-13 12:02:20,618 INFO    MainThread:27108 [wandb_setup.py:_flush():76] Configure stats pid to 27108
2024-03-13 12:02:20,618 INFO    MainThread:27108 [wandb_setup.py:_flush():76] Loading settings from C:\Users\USER\.config\wandb\settings
2024-03-13 12:02:20,618 INFO    MainThread:27108 [wandb_setup.py:_flush():76] Loading settings from C:\Users\USER\Desktop\mini-marl\vdn\wandb\settings
2024-03-13 12:02:20,618 INFO    MainThread:27108 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-13 12:02:20,618 INFO    MainThread:27108 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-13 12:02:20,628 INFO    MainThread:27108 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'vdn\\main.py', 'program_abspath': 'C:\\Users\\USER\\Desktop\\mini-marl\\vdn\\main.py', 'program': 'C:\\Users\\USER\\Desktop\\mini-marl\\vdn\\main.py'}
2024-03-13 12:02:20,628 INFO    MainThread:27108 [wandb_init.py:_log_setup():526] Logging user logs to C:\Users\USER\Desktop\mini-marl\vdn\wandb\run-20240313_120220-19hno4zp\logs\debug.log
2024-03-13 12:02:20,628 INFO    MainThread:27108 [wandb_init.py:_log_setup():527] Logging internal logs to C:\Users\USER\Desktop\mini-marl\vdn\wandb\run-20240313_120220-19hno4zp\logs\debug-internal.log
2024-03-13 12:02:20,628 INFO    MainThread:27108 [wandb_init.py:init():566] calling init triggers
2024-03-13 12:02:20,629 INFO    MainThread:27108 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'use_wandb': True, 'entity_name': 'singfor7012', 'env_name': 'ma_gym:Checkers-v0', 'experiment_name': 'vdn', 'use_cuda': False, 'n_training_threads': 12, 'use_render': False, 'use_time_sleep': False, 'sleep_second': 0.5, 'seed': 42, 'fix_seed': True, 'epsilon_anneal_episode': 60000, 'max_epsilon': 0.9, 'min_epsilon': 0.05, 'lr': 0.0001, 'gamma': 0.99, 'batch_size': 32, 'max_episodes': 100000, 'max_step': 100, 'step_cost': -0.01, 'chunk_size': 10, 'update_iter': 1, 'update_target_interval': 50, 'grad_clip_norm': 0.1, 'decide_target': 'double_dqn', 'decide_network': 'q_net', 'use_recurrent': True, 'test_interval': 10, 'test_episodes': 10, 'buffer_limit': 10000, 'eps': 1e-06, 'alpha': 0.4, 'beta': 0.4, 'update_alpha_beta': True}
2024-03-13 12:02:20,629 INFO    MainThread:27108 [wandb_init.py:init():616] starting backend
2024-03-13 12:02:20,629 INFO    MainThread:27108 [wandb_init.py:init():620] setting up manager
2024-03-13 12:02:20,636 INFO    MainThread:27108 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-13 12:02:20,638 INFO    MainThread:27108 [wandb_init.py:init():628] backend started and connected
2024-03-13 12:02:20,654 INFO    MainThread:27108 [wandb_init.py:init():720] updated telemetry
2024-03-13 12:02:20,720 INFO    MainThread:27108 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-13 12:02:21,353 INFO    MainThread:27108 [wandb_run.py:_on_init():2262] communicating current version
2024-03-13 12:02:21,445 INFO    MainThread:27108 [wandb_run.py:_on_init():2271] got version response upgrade_message: "wandb version 0.16.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-03-13 12:02:21,445 INFO    MainThread:27108 [wandb_init.py:init():804] starting run threads in backend
2024-03-13 12:02:40,277 INFO    MainThread:27108 [wandb_run.py:_console_start():2241] atexit reg
2024-03-13 12:02:40,278 INFO    MainThread:27108 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-13 12:02:40,278 INFO    MainThread:27108 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-13 12:02:40,278 INFO    MainThread:27108 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-13 12:02:40,279 INFO    MainThread:27108 [wandb_init.py:init():847] run started, returning control to user process
2024-03-13 12:10:12,549 WARNING MsgRouterThr:27108 [router.py:message_loop():77] message_loop has been closed
